### PR TITLE
add "makulerad" pdf templates

### PR DESCRIPTION
**Pull request by JILeXanDR**
https://app.asana.com/0/1191454108886202/1200005093935245
New certificates cancel functionality requires to add "makulerad" watermark for cancelled certificates.
To achieve this need to add extra PDF templates with prepared watermark.

### CODE REVIEW

**Review by hannes-md — APPROVED** [review]
Can't see them ofc but I assume they are correct :)

**Comment by JILeXanDR** [comment]
@hannes-md  You can)
image

**Comment by hannes-md** [comment]
Haha, you sure didn't expect this to happen!! 🤣 
image

**Comment by hannes-md** [comment]
but yeah I did have a look now. :shipit:

**Pull request merged**
